### ISSUE TITLE
Doesn't handle filenames with spaces (it ignores the part before the space)

### ISSUE THREAD

**Issue by Zerowalker** [viz-rs/form-data#5]
As title says.
Not sure if it's a bug or if i am missing how to handle it on the client side.

Basically if the filename is: "Foo bar.txt" the filename received will be "bar.txt"

**Comment by fundon** [comment]
Currently, just only supports on server side.

**Comment by fundon** [comment]
Released in v0.2.4.

**Comment by Zerowalker** [comment]
it's on the server side, so i am sending from browser/javascript and rust server receiving so to speak.

**Comment by fundon** [comment]
You can reopen it, if it cant fix your issue.

**Comment by Zerowalker** [comment]
It seems to work, i can't even get it to not work even with older versions now, odd but great!
