### ISSUE TITLE
Which types can T be for FormData?

### ISSUE THREAD

**Issue by nifker** [viz-rs/form-data#6]
When Im trying to call next() from futures_util::stream::Stream on FormData<T> I always get an error that Stream is not implement for T, in my case I tried &[u8], Box<[u8]> and Vec<[u8]> - all of them didnt work.

```
error[E0599]: the method `next` exists for struct `FormData<Vec<u8>>`, but its trait bounds were not satisfied
  --> src/image.rs:58:13
   |
58 |         form_data.next();
   |                   ^^^^ method cannot be called on `FormData<Vec<u8>>` due to unsatisfied trait bounds
   |
  ::: /home/nifker/.cargo/registry/src/github.com-1ecc6299db9ec823/form-data-0.2.6/src/form.rs:18:1
   |
18 | pub struct FormData<T> {
   | ----------------------
   | |
   | doesn't satisfy `FormData<Vec<u8>>: StreamExt`
   | doesn't satisfy `FormData<Vec<u8>>: futures_util::Stream`
   |
   = note: the following trait bounds were not satisfied:
           `FormData<Vec<u8>>: futures_util::Stream`
           which is required by `FormData<Vec<u8>>: StreamExt`

```

**Comment by fundon** [comment]
@nifker uses [hyper::Body](https://docs.rs/hyper/0.14.14/hyper/struct.Body.html) then we can use [Field::bytes](https://docs.rs/form-data/0.2.6/form_data/struct.Field.html#method.bytes) to read bytes.

**Comment by nifker** [comment]
and when I use tiny_http?

**Comment by fundon** [comment]
Do you have an example that I can adapt?

**Comment by nifker** [comment]
tiny_http provides this function: https://docs.rs/tiny_http/0.9.0/tiny_http/struct.Request.html#method.as_reader

**Comment by fundon** [comment]
Thanks, I add an example case for tiny_http.

**Comment by fundon** [comment]
Landed in https://docs.rs/form-data/0.3.0/form_data/. Enable the `sync` feature. See https://github.com/viz-rs/form-data/blob/master/examples/tiny_http.rs.

**Comment by nifker** [comment]
'form-data' fails to parse the data from my form for some reason I get Err(invalid part header).
This is the multipart data the server received: https://paste.gg/p/anonymous/8cead24091f64098817d17b2d2e2c2db

**Comment by fundon** [comment]
@nifker See https://github.com/viz-rs/form-data/blob/master/tests/tiny-body.rs

It follows rfc7578, so uses `CRLF` to split lines.

**Comment by nifker** [comment]
And what am I supposed to do about it? I can check if its CRLF, but I get it like that from my browser sent.

**Comment by fundon** [comment]
Which browser? And Can u post the HTML Form?

**Comment by nifker** [comment]
Im on Firefox 78.15.0ESR. The form is the following: https://gitlab.com/nifker/webserver/-/blob/main/http/upload.html

**Comment by nifker** [comment]
The error definitely occurs in this function: https://github.com/viz-rs/form-data/blob/master/src/utils.rs#L21

**Comment by nifker** [comment]
Im unsure now I just do it similar to the example of yours but it panics each time.
`		let m = req
			.headers()
			.iter()
			.find(|h: &&Header| h.field.equiv("Content-Type"))
			.map(|h| h.value.clone())
			.and_then(|val| val.as_str().parse::<mime::Mime>().ok())
			.unwrap();
		let boundary = m.get_param(mime::BOUNDARY).unwrap().as_str();

		let mut form_data = FormData::new(req.as_reader(), &boundary);

		while let Some(item) = form_data.next() {
			println!("{:?}", item.unwrap());
		}`

**Comment by fundon** [comment]
> it seems like I actually need to read all bytes of a field first before I can read the next one.
Yes, you need to read one field data to continue reading the next one, this is the stream.

A Field has four methods to read bytes. https://github.com/viz-rs/form-data/blob/master/src/sync.rs#L105-L150.

**Comment by fundon** [comment]
@nifker Is it working?

**Comment by nifker** [comment]
Oh I forgot to actually reply, yes it is working. Thank you!
